export const UPDATE_DYNAMICCOMPONENT_LIST = 'UPDATE_DYNAMICCOMPONENT_LIST' // 更新动态组件
export const UPDATE_TOGGLE = 'UPDATE_TOGGLE' // 更新开关
export const UPDATE_EDITCOMPONENTID = 'UPDATE_EDITCOMPONENTID' // 当前编辑的组件
export const UPDATE_GRAGGABLE = 'UPDATE_GRAGGABLE' // 更新拖拽对象
export const UPDATE_TIMESPAN = 'UPDATE_TIMESPAN' // 更新时间戳
export const UPDATE_BASE_STATE = 'UPDATE_BASE_STATE' // 简单更一个状态
